### ISSUE TITLE
xeus-python version is 0.7.1

### ISSUE THREAD

**Issue by jtpio** [deathbeds/_fam#8]
Impressive Binder!

Giving it a quick try, it looks like the version of `xeus-python` is still `0.7.1`: 

![image](https://user-images.githubusercontent.com/591645/88917148-90bd2200-d267-11ea-8fb5-99cf451aa88d.png)

The latest `0.8+` includes magics and also includes the `debugger` key in the kernel spec metadata (so the debugger frontend can be displayed).

**Comment by bollwyvl** [comment]
Ha, nice, thanks. We should pin that for sure!

Any other fun tricks we should share? I don't remember if we've loaded up
xidgets... debugging inside a deep trailet link chain sounds tear-jerking
😹.

We also might switch it up to a raw dockerfile, as we probably need a
little better entropy management.

**Comment by bollwyvl** [comment]
Update here: the offender was... `xeus-cling` :astonished: 
```
Problem: package xeus-cling-0.5.0-he513fc3_0 requires xeus >=0.19.1,<0.20.0a0, but none of the providers can be installed
Problem: package xeus-python-0.8.3-py36hdb11119_0 requires xeus >=0.24.1,<0.25.0a0, but none of the providers can be installed
```

**Comment by bollwyvl** [comment]
(Also `xeus-sqlite`)

**Comment by bollwyvl** [comment]
Welp, we've gotten the magic-having xpython up and it into the 07-25-2020 MVP, which is as good as shipped, so I don't think there's much else to fix at this point. 

![Screenshot from 2020-08-03 20-55-18](https://user-images.githubusercontent.com/45380/89240975-aa45cd00-d5cb-11ea-8d8a-0cc097b13de6.png)

Being able to debug an `@interact` is **pretty darned fun**.

We _could_ add a second environment for xeus-cling and xeus-sqlite, (heck, I want a pypy env, for good measure) but I guess we can close this out for now.

**Comment by jtpio** [comment]
Nice, thanks!
